{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "cortex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cortex.name" . }}
    chart: {{ template "cortex.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.rbac.pspEnabled }}
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "cortex.fullname" . }}]
{{- end }}
{{- if or .Values.sidecar.rules.enabled .Values.sidecar.alertmanager.enabled }}
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
{{- end }}
{{- end }}

